# Generated by Django 5.2.9 on 2025-12-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dm_photos/'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
